services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: usermanagement
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app_pw
    ports:
      - "5444:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  pgdata:
